version: "3"

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile-postgres
    environment:
      POSTGRES_USER: sciencecache
      POSTGRES_PASSWORD: 7wRwACm#BrWmF
    ports:
      - 5433:5432
  # sciencecache-service:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile-service
  #   environment:
  #     SCIENCECACHE_SERVICE_ROOT: ./
  #   ports:
  #     - 8000:8000